/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Check API health. */
        get: operations["Health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/household": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the current household profile. */
        get: operations["HouseholdRoute_getCurrent"];
        /** @description Create or update the current household profile. */
        put: operations["HouseholdRoute_upsert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meal-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the current meal plan. */
        get: operations["MealPlanRoute_getCurrent"];
        /** @description Create or update the current meal plan. */
        put: operations["MealPlanRoute_upsert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all recipes for the current household. */
        get: operations["Recipes_list"];
        put?: never;
        /** @description Create a new recipe. */
        post: operations["Recipes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a recipe by its identifier. */
        get: operations["Recipes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shopping-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the current shopping list. */
        get: operations["ShoppingListRoute_getCurrent"];
        /** @description Create or update the current shopping list. */
        put: operations["ShoppingListRoute_upsert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store-cupboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the current store cupboard. */
        get: operations["StoreCupboardRoute_getCurrent"];
        /** @description Create or update the current store cupboard. */
        put: operations["StoreCupboardRoute_upsert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request body for creating a new recipe. */
        CreateRecipeRequest: {
            /** @description Recipe title. */
            title: string;
            /** @description Recipe description. */
            description?: string;
            /**
             * Format: int32
             * @description Number of servings. Defaults to 4.
             * @default 4
             */
            servings: number;
            /**
             * Format: int32
             * @description Preparation time in minutes.
             */
            prepTimeMinutes?: number;
            /**
             * Format: int32
             * @description Cooking time in minutes.
             */
            cookTimeMinutes?: number;
            /** @description List of ingredients. */
            ingredients: components["schemas"]["Ingredient"][];
            /** @description Cooking steps in order. */
            steps: string[];
            /** @description Recipe tags. */
            tags?: string[];
            /** @description Whether the recipe is publicly visible. */
            isPublic?: boolean;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Common dietary restrictions.
         * @enum {string}
         */
        DietaryRestriction: "None" | "Vegetarian" | "Vegan" | "GlutenFree" | "DairyFree" | "NutFree" | "EggFree" | "ShellfishFree" | "SoyFree" | "Halal" | "Kosher";
        /**
         * @description Category of food item for grouping in shopping lists.
         * @enum {string}
         */
        FoodCategory: "FruitAndVeg" | "Meat" | "Fish" | "Dairy" | "Bakery" | "Grains" | "Canned" | "Frozen" | "HerbsAndSpices" | "Condiments" | "Drinks" | "Snacks" | "Other";
        /** @description Health check response. */
        HealthCheckResponse: {
            /** @description Health status. */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Household profile in API responses. */
        Household: {
            /** @description Household identifier. */
            id: string;
            /** @description Household display name. */
            name: string;
            /** @description Household invite code. */
            inviteCode: string;
            /**
             * Format: date-time
             * @description ISO timestamp for household creation.
             */
            createdAt: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description An ingredient with quantity and unit.
         *
         *     Note: Quantity is represented as float64 in the spec. The C# domain model
         *     uses `decimal` for precision; consumers should treat this as a decimal value.
         */
        Ingredient: {
            /** @description Ingredient name. */
            name: string;
            /**
             * Format: double
             * @description Amount required.
             */
            quantity: number;
            /** @description Measurement unit. */
            unit: components["schemas"]["Unit"];
            /** @description Food category for shopping list grouping. */
            category: components["schemas"]["FoodCategory"];
            /** @description Optional preparation notes (e.g., "finely chopped"). */
            notes?: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Current meal plan for a household. */
        MealPlan: {
            /** @description Meal plan identifier. */
            id: string;
            /** @description Owning household identifier. */
            householdId: string;
            /** @description Meal plan title. */
            title: string;
            /**
             * Format: date
             * @description Meal plan start date (YYYY-MM-DD).
             */
            startDate: string;
            /**
             * Format: date
             * @description Meal plan end date (YYYY-MM-DD).
             */
            endDate: string;
            /** @description Planned meals for the period. */
            meals: components["schemas"]["MealSlot"][];
            /**
             * Format: date-time
             * @description ISO timestamp when this meal plan was created.
             */
            createdAt: string;
        } & {
            [key: string]: unknown;
        };
        /** @description A planned meal entry for a specific date. */
        MealSlot: {
            /**
             * Format: date
             * @description Date for this planned meal (YYYY-MM-DD).
             */
            date: string;
            /** @description Meal type label. */
            mealType: string;
            /** @description Linked recipe identifier. */
            recipeId: string;
            /**
             * Format: int32
             * @description Number of servings planned.
             */
            servings: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Type of meal in a day.
         * @enum {string}
         */
        MealType: "Breakfast" | "Lunch" | "Dinner" | "Snack";
        /** @description A recipe in API responses. */
        Recipe: {
            /** @description Recipe identifier. */
            id: string;
            /** @description Recipe title. */
            title: string;
            /** @description Recipe description. */
            description?: string;
            /**
             * Format: int32
             * @description Number of servings.
             */
            servings: number;
            /**
             * Format: int32
             * @description Preparation time in minutes.
             */
            prepTimeMinutes?: number;
            /**
             * Format: int32
             * @description Cooking time in minutes.
             */
            cookTimeMinutes?: number;
            /** @description List of ingredients. */
            ingredients: components["schemas"]["Ingredient"][];
            /** @description Cooking steps in order. */
            steps: string[];
            /** @description Recipe tags. */
            tags: string[];
            /** @description Whether the recipe is publicly visible. */
            isPublic: boolean;
        } & {
            [key: string]: unknown;
        };
        /** @description Item on a shopping list. */
        ShoppingItem: {
            /** @description Item name. */
            name: string;
            /**
             * Format: double
             * @description Quantity to purchase.
             */
            quantity: number;
            /** @description Unit label for quantity. */
            unit: string;
            /** @description Category label for grouping. */
            category: string;
            /** @description Whether the item has been checked off. */
            isChecked: boolean;
        } & {
            [key: string]: unknown;
        };
        /** @description Current shopping list for a household. */
        ShoppingList: {
            /** @description Shopping list identifier. */
            id: string;
            /** @description Owning household identifier. */
            householdId: string;
            /** @description Linked meal plan identifier. */
            mealPlanId: string;
            /** @description Shopping list items. */
            items: components["schemas"]["ShoppingItem"][];
            /**
             * Format: date-time
             * @description ISO timestamp when this list was created or updated.
             */
            createdAt: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Current store cupboard for a household. */
        StoreCupboard: {
            /** @description Store cupboard identifier. */
            id: string;
            /** @description Owning household identifier. */
            householdId: string;
            /** @description Stored cupboard items. */
            items: components["schemas"]["StoreCupboardItem"][];
            /**
             * Format: date-time
             * @description ISO timestamp when this cupboard was last updated.
             */
            updatedAt: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Item in the household store cupboard. */
        StoreCupboardItem: {
            /** @description Item name. */
            name: string;
            /** @description Category label for grouping. */
            category: string;
            /** @description Whether the item is always stocked. */
            alwaysStocked: boolean;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Unit of measurement for ingredients.
         * @enum {string}
         */
        Unit: "Piece" | "Grams" | "Kilograms" | "Millilitres" | "Litres" | "Teaspoon" | "Tablespoon" | "Cup" | "Pinch" | "Handful";
        /** @description Request body for creating or updating household details. */
        UpsertHouseholdRequest: {
            /** @description Household display name. */
            name: string;
            /** @description Optional invite code to assign to this household. */
            inviteCode?: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Request body for creating or updating the current meal plan. */
        UpsertMealPlanRequest: {
            /** @description Meal plan title. */
            title: string;
            /**
             * Format: date
             * @description Meal plan start date (YYYY-MM-DD).
             */
            startDate: string;
            /**
             * Format: date
             * @description Meal plan end date (YYYY-MM-DD).
             */
            endDate: string;
            /** @description Planned meals for the period. */
            meals: components["schemas"]["MealSlot"][];
        } & {
            [key: string]: unknown;
        };
        /** @description Request body for creating or updating the current shopping list. */
        UpsertShoppingListRequest: {
            /** @description Linked meal plan identifier. */
            mealPlanId: string;
            /** @description Shopping list items. */
            items: components["schemas"]["ShoppingItem"][];
        } & {
            [key: string]: unknown;
        };
        /** @description Request body for creating or updating the store cupboard. */
        UpsertStoreCupboardRequest: {
            /** @description Stored cupboard items. */
            items: components["schemas"]["StoreCupboardItem"][];
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckResponse"];
                };
            };
        };
    };
    HouseholdRoute_getCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Household"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HouseholdRoute_upsert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertHouseholdRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Household"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MealPlanRoute_getCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealPlan"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MealPlanRoute_upsert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertMealPlanRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealPlan"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Recipes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"][];
                };
            };
        };
    };
    Recipes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecipeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Recipes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShoppingListRoute_getCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingList"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShoppingListRoute_upsert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertShoppingListRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingList"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StoreCupboardRoute_getCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreCupboard"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StoreCupboardRoute_upsert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertStoreCupboardRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreCupboard"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
