/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/api/health': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['Health_check'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/households/invites': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['HouseholdInvites_list'];
        put?: never;
        post: operations['HouseholdInvites_create'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/households/invites/{inviteId}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations['HouseholdInvites_revoke'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/invites/redeem': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations['InviteRedemption_redeem'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/register/complete': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations['Registration_complete'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateHouseholdInviteRequest: {
            /** Format: int32 */
            maxUses: number;
            /** Format: int32 */
            expiresInDays?: number;
            regenerate?: boolean;
            idempotencyKey: string;
        } & {
            [key: string]: unknown;
        };
        CreateHouseholdInviteResponse: {
            code: string;
            /** Format: int32 */
            maxUses: number;
            /** Format: int32 */
            remainingUses: number;
            /** Format: date-time */
            expiresAt: string;
        } & {
            [key: string]: unknown;
        };
        ErrorResponse: {
            message: string;
            code?: string;
        } & {
            [key: string]: unknown;
        };
        HealthCheckResponse: {
            status: string;
        } & {
            [key: string]: unknown;
        };
        HouseholdSummary: {
            id: string;
            name: string;
        } & {
            [key: string]: unknown;
        };
        InviteRedeemRequest: {
            code: string;
        } & {
            [key: string]: unknown;
        };
        InviteRedeemResponse: {
            joinIntentToken: string;
            household: components['schemas']['HouseholdSummary'];
            /** Format: int32 */
            remainingUses: number;
            /** Format: date-time */
            expiresAt: string;
        } & {
            [key: string]: unknown;
        };
        InviteStatus: {
            id: string;
            codeMasked: string;
            /** Format: int32 */
            maxUses: number;
            /** Format: int32 */
            remainingUses: number;
            /** Format: date-time */
            expiresAt: string;
            /** @enum {string} */
            status: 'active' | 'expired' | 'exhausted' | 'revoked';
        } & {
            [key: string]: unknown;
        };
        ListHouseholdInvitesResponse: {
            invites: components['schemas']['InviteStatus'][];
        } & {
            [key: string]: unknown;
        };
        RegisterCompleteRequest: {
            name: string;
            email?: string;
            password?: string;
            /** @enum {string} */
            householdAction: 'create' | 'join';
            householdName?: string;
            joinIntentToken?: string;
            idempotencyKey: string;
        } & {
            [key: string]: unknown;
        };
        RegisterCompleteResponse: {
            userId: string;
            householdId: string;
            /** @enum {string} */
            actionApplied: 'create' | 'join';
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['HealthCheckResponse'];
                };
            };
        };
    };
    HouseholdInvites_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ListHouseholdInvitesResponse'];
                };
            };
            /** @description Access is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
        };
    };
    HouseholdInvites_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['CreateHouseholdInviteRequest'];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['CreateHouseholdInviteResponse'];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
            /** @description Access is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
            /** @description Client error */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
            /** @description Service unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
        };
    };
    HouseholdInvites_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
        };
    };
    InviteRedemption_redeem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['InviteRedeemRequest'];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['InviteRedeemResponse'];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
            /** @description Client error */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
            /** @description Client error */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
            /** @description Service unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
        };
    };
    Registration_complete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['RegisterCompleteRequest'];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['RegisterCompleteResponse'];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
            /** @description Access is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
            /** @description Client error */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
            /** @description Client error */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
            /** @description Service unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
        };
    };
}
