/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Check API health. */
        get: operations["Health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a new recipe. */
        post: operations["Recipes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a recipe by its identifier. */
        get: operations["Recipes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request body for creating a new recipe. */
        CreateRecipeRequest: {
            /** @description Recipe title. */
            title: string;
            /** @description Recipe description. */
            description?: string;
            /**
             * Format: int32
             * @description Number of servings. Defaults to 4.
             * @default 4
             */
            servings: number;
            /**
             * Format: int32
             * @description Preparation time in minutes.
             */
            prepTimeMinutes?: number;
            /**
             * Format: int32
             * @description Cooking time in minutes.
             */
            cookTimeMinutes?: number;
            /** @description List of ingredients. */
            ingredients: components["schemas"]["Ingredient"][];
            /** @description Cooking steps in order. */
            steps: string[];
            /** @description Recipe tags. */
            tags?: string[];
            /** @description Whether the recipe is publicly visible. */
            isPublic?: boolean;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Common dietary restrictions.
         * @enum {string}
         */
        DietaryRestriction: "None" | "Vegetarian" | "Vegan" | "GlutenFree" | "DairyFree" | "NutFree" | "EggFree" | "ShellfishFree" | "SoyFree" | "Halal" | "Kosher";
        /**
         * @description Category of food item for grouping in shopping lists.
         * @enum {string}
         */
        FoodCategory: "FruitAndVeg" | "Meat" | "Fish" | "Dairy" | "Bakery" | "Grains" | "Canned" | "Frozen" | "HerbsAndSpices" | "Condiments" | "Drinks" | "Snacks" | "Other";
        /** @description Health check response. */
        HealthCheckResponse: {
            /** @description Health status. */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description An ingredient with quantity and unit.
         *
         *     Note: Quantity is represented as float64 in the spec. The C# domain model
         *     uses `decimal` for precision; consumers should treat this as a decimal value.
         */
        Ingredient: {
            /** @description Ingredient name. */
            name: string;
            /**
             * Format: double
             * @description Amount required.
             */
            quantity: number;
            /** @description Measurement unit. */
            unit: components["schemas"]["Unit"];
            /** @description Food category for shopping list grouping. */
            category: components["schemas"]["FoodCategory"];
            /** @description Optional preparation notes (e.g., "finely chopped"). */
            notes?: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Type of meal in a day.
         * @enum {string}
         */
        MealType: "Breakfast" | "Lunch" | "Dinner" | "Snack";
        /** @description A recipe in API responses. */
        Recipe: {
            /** @description Recipe identifier. */
            id: string;
            /** @description Recipe title. */
            title: string;
            /** @description Recipe description. */
            description?: string;
            /**
             * Format: int32
             * @description Number of servings.
             */
            servings: number;
            /**
             * Format: int32
             * @description Preparation time in minutes.
             */
            prepTimeMinutes?: number;
            /**
             * Format: int32
             * @description Cooking time in minutes.
             */
            cookTimeMinutes?: number;
            /** @description List of ingredients. */
            ingredients: components["schemas"]["Ingredient"][];
            /** @description Cooking steps in order. */
            steps: string[];
            /** @description Recipe tags. */
            tags: string[];
            /** @description Whether the recipe is publicly visible. */
            isPublic: boolean;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Unit of measurement for ingredients.
         * @enum {string}
         */
        Unit: "Piece" | "Grams" | "Kilograms" | "Millilitres" | "Litres" | "Teaspoon" | "Tablespoon" | "Cup" | "Pinch" | "Handful";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckResponse"];
                };
            };
        };
    };
    Recipes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecipeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Recipes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
